### PR TITLE
Bump dependencies for projects + move doc-builder attributes to project.clj (JDK 11)

### PR DESCRIPTION
**Pull request by drew-patel**
Updated dependencies for JDK 11 support

### CODE REVIEW

**Review by jpgauthier — COMMENTED** [review]
:shipit:

**Comment by jpgauthier** [comment]
@drew-patel Can you add a link to the documentation of why it's need to pass down the attributes as JVM flags now?

**Comment by drew-patel** [comment]
Here's the link: 
https://docs.oracle.com/en/java/javase/13/security/java-api-xml-processing-jaxp-security-guide.html#GUID-3FB69003-1E4A-435C-B519-4B9D07630460

**Review by Elknar — COMMENTED** [review]
looks fine by me too.

The jvm opts are the equivalent of the attributes. The doc doesn't say to use them instead, but we have little option given that the names are no longer recognized

**Pull request merged**
